USE [master]
GO
/****** Object:  Database [Audiencia]    Script Date: 28/08/2025 8:15:25 ******/
CREATE DATABASE [Audiencia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Audiencia', FILENAME = N'C:\Users\SAE Chaco\Audiencia.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Audiencia_log', FILENAME = N'C:\Users\SAE Chaco\Audiencia_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Audiencia] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Audiencia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Audiencia] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Audiencia] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Audiencia] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Audiencia] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Audiencia] SET ARITHABORT OFF 
GO
ALTER DATABASE [Audiencia] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Audiencia] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Audiencia] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Audiencia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Audiencia] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Audiencia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Audiencia] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Audiencia] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Audiencia] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Audiencia] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Audiencia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Audiencia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Audiencia] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Audiencia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Audiencia] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Audiencia] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Audiencia] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Audiencia] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Audiencia] SET  MULTI_USER 
GO
ALTER DATABASE [Audiencia] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Audiencia] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Audiencia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Audiencia] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Audiencia] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Audiencia] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Audiencia] SET QUERY_STORE = OFF
GO
USE [Audiencia]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Audiencias]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Audiencias](
	[IdAudiencia] [int] IDENTITY(1,1) NOT NULL,
	[CorreoElectronico] [nvarchar](100) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[DNI] [nvarchar](20) NOT NULL,
	[NombreEmpresa] [nvarchar](100) NOT NULL,
	[IdCargo] [int] NOT NULL,
	[IdClasificacion] [int] NOT NULL,
	[IdEstado] [int] NOT NULL,
	[AtendidoPor] [int] NOT NULL,
	[DerivadoA] [nvarchar](100) NULL,
	[Estado] [nvarchar](50) NULL,
	[Asunto] [text] NOT NULL,
 CONSTRAINT [PK__Audienci__D24CE72D100830B4] PRIMARY KEY CLUSTERED 
(
	[IdAudiencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cargo]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cargo](
	[IdCargo] [int] IDENTITY(1,1) NOT NULL,
	[NombreCargo] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Cargo__6C985625FA83D6F6] PRIMARY KEY CLUSTERED 
(
	[IdCargo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clasificaciones]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clasificaciones](
	[IDClasificacion] [int] IDENTITY(1,1) NOT NULL,
	[Clasificacion] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Clasific__28ABDECE9E13BC5F] PRIMARY KEY CLUSTERED 
(
	[IDClasificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmailRequest]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmailRequest](
	[IdEmail] [int] IDENTITY(1,1) NOT NULL,
	[Destinatario] [varchar](255) NOT NULL,
	[CodigoRecuperacion] [varchar](100) NOT NULL,
	[CodigoRecuperacionExpira] [datetime] NOT NULL,
 CONSTRAINT [PK_EmailRequest] PRIMARY KEY CLUSTERED 
(
	[IdEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empleado]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[IdEmpleado] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Apellido] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Empleado__CE6D8B9EDEB47468] PRIMARY KEY CLUSTERED 
(
	[IdEmpleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estado]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado](
	[IDEstado] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Estado__45504034F1EB29B8] PRIMARY KEY CLUSTERED 
(
	[IDEstado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 28/08/2025 8:15:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Correo] [varchar](50) NULL,
	[Clave] [varchar](50) NULL,
	[EsAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Audiencias_AtendidoPor]    Script Date: 28/08/2025 8:15:25 ******/
CREATE NONCLUSTERED INDEX [IX_Audiencias_AtendidoPor] ON [dbo].[Audiencias]
(
	[AtendidoPor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Audiencias_IdCargo]    Script Date: 28/08/2025 8:15:25 ******/
CREATE NONCLUSTERED INDEX [IX_Audiencias_IdCargo] ON [dbo].[Audiencias]
(
	[IdCargo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Audiencias_IdClasificacion]    Script Date: 28/08/2025 8:15:25 ******/
CREATE NONCLUSTERED INDEX [IX_Audiencias_IdClasificacion] ON [dbo].[Audiencias]
(
	[IdClasificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Audiencias_IdEstado]    Script Date: 28/08/2025 8:15:25 ******/
CREATE NONCLUSTERED INDEX [IX_Audiencias_IdEstado] ON [dbo].[Audiencias]
(
	[IdEstado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Audiencias] ADD  DEFAULT (getdate()) FOR [Fecha]
GO
ALTER TABLE [dbo].[EmailRequest] ADD  DEFAULT (getdate()) FOR [CodigoRecuperacionExpira]
GO
ALTER TABLE [dbo].[Audiencias]  WITH CHECK ADD  CONSTRAINT [FK_Audiencia_Cargo] FOREIGN KEY([IdCargo])
REFERENCES [dbo].[Cargo] ([IdCargo])
GO
ALTER TABLE [dbo].[Audiencias] CHECK CONSTRAINT [FK_Audiencia_Cargo]
GO
ALTER TABLE [dbo].[Audiencias]  WITH CHECK ADD  CONSTRAINT [FK_Audiencia_Clasificacion] FOREIGN KEY([IdClasificacion])
REFERENCES [dbo].[Clasificaciones] ([IDClasificacion])
GO
ALTER TABLE [dbo].[Audiencias] CHECK CONSTRAINT [FK_Audiencia_Clasificacion]
GO
ALTER TABLE [dbo].[Audiencias]  WITH CHECK ADD  CONSTRAINT [FK_Audiencia_Empleado] FOREIGN KEY([AtendidoPor])
REFERENCES [dbo].[Empleado] ([IdEmpleado])
GO
ALTER TABLE [dbo].[Audiencias] CHECK CONSTRAINT [FK_Audiencia_Empleado]
GO
ALTER TABLE [dbo].[Audiencias]  WITH CHECK ADD  CONSTRAINT [FK_Audiencia_Estado] FOREIGN KEY([IdEstado])
REFERENCES [dbo].[Estado] ([IDEstado])
GO
ALTER TABLE [dbo].[Audiencias] CHECK CONSTRAINT [FK_Audiencia_Estado]
GO
USE [master]
GO
ALTER DATABASE [Audiencia] SET  READ_WRITE 
GO
