-- Crear la base de datos sin rutas físicas (SQL Server asignará por defecto en /var/opt/mssql/data)
CREATE DATABASE [Audiencias];
GO

-- Habilitar FullText si está instalado
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [Audiencias].[dbo].[sp_fulltext_database] @action = 'enable';
END
GO

-- Opciones de configuración recomendadas
ALTER DATABASE [Audiencias] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [Audiencias] SET ANSI_NULLS OFF;
ALTER DATABASE [Audiencias] SET ANSI_PADDING OFF;
ALTER DATABASE [Audiencias] SET ANSI_WARNINGS OFF;
ALTER DATABASE [Audiencias] SET ARITHABORT OFF;
ALTER DATABASE [Audiencias] SET AUTO_CLOSE OFF;
ALTER DATABASE [Audiencias] SET AUTO_SHRINK OFF;
ALTER DATABASE [Audiencias] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [Audiencias] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [Audiencias] SET CURSOR_DEFAULT  GLOBAL;
ALTER DATABASE [Audiencias] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [Audiencias] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [Audiencias] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [Audiencias] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [Audiencias] SET ENABLE_BROKER;
ALTER DATABASE [Audiencias] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [Audiencias] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [Audiencias] SET TRUSTWORTHY OFF;
ALTER DATABASE [Audiencias] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [Audiencias] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [Audiencias] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [Audiencias] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [Audiencias] SET RECOVERY FULL;
ALTER DATABASE [Audiencias] SET MULTI_USER;
ALTER DATABASE [Audiencias] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [Audiencias] SET DB_CHAINING OFF;
ALTER DATABASE [Audiencias] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [Audiencias] SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE [Audiencias] SET ACCELERATED_DATABASE_RECOVERY = OFF;
ALTER DATABASE [Audiencias] SET QUERY_STORE = ON;
ALTER DATABASE [Audiencias] SET QUERY_STORE (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    INTERVAL_LENGTH_MINUTES = 60,
    MAX_STORAGE_SIZE_MB = 1000,
    QUERY_CAPTURE_MODE = AUTO,
    SIZE_BASED_CLEANUP_MODE = AUTO,
    MAX_PLANS_PER_QUERY = 200,
    WAIT_STATS_CAPTURE_MODE = ON
);
ALTER DATABASE [Audiencias] SET READ_WRITE;
GO
